version: '3.8'
services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      minha-rede-linguagens-api:
        aliases:
          - banco-de-dados
  linguagens-api:
    image: fernandesrh/linguagens-api:1.0.0
    container_name: linguagens-api-bridge
    restart: always
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@cluster0.bfibisr.mongodb.net/aluraDb?retryWrites=true&w=majority
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
       minha-rede-linguagens-api:
networks:
   minha-rede-linguagens-api:
    driver: bridge
